/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import database.Koneksi;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DIKYPUT PC
 */
public class pelanggan extends javax.swing.JFrame {
    DefaultTableModel model;
  public Connection conn = Koneksi.getKoneksi();
    public pelanggan() {
        initComponents();
    String [] judul = {"NIK", "Nama", "Alamat", "Telepon"};
       model =new DefaultTableModel(judul, 0);
               tpelanggan.setModel(model);
             tampilkan();
    }
    public void bersih() {
nik.setText("");
ap.setText("");
np.setText("");
tp.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tpelanggan = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        cetak = new javax.swing.JButton();
        Kembalia = new javax.swing.JButton();
        nik = new javax.swing.JTextField();
        np = new javax.swing.JTextField();
        ap = new javax.swing.JTextField();
        tp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tpelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tpelanggan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 560, 300));

        hapus.setBackground(new java.awt.Color(0, 153, 255));
        hapus.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("HAPUS");
        hapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 90, 30));

        cetak.setBackground(new java.awt.Color(0, 153, 255));
        cetak.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cetak.setForeground(new java.awt.Color(255, 255, 255));
        cetak.setText("CETAK");
        cetak.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        getContentPane().add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 90, 30));

        Kembalia.setBackground(new java.awt.Color(255, 51, 51));
        Kembalia.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        Kembalia.setForeground(new java.awt.Color(255, 255, 255));
        Kembalia.setText("Kembali");
        Kembalia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Kembalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliaActionPerformed(evt);
            }
        });
        getContentPane().add(Kembalia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 90, 30));
        getContentPane().add(nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 150, 20));

        np.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npActionPerformed(evt);
            }
        });
        getContentPane().add(np, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 150, -1));
        getContentPane().add(ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 150, 20));
        getContentPane().add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 150, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 250, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pelanggan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/unnamed (2).jpg"))); // NOI18N
        jLabel2.setText("j");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 200, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/unnamed (2).jpg"))); // NOI18N
        jLabel3.setText("j");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 420, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed

        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
            cn.createStatement().executeUpdate("delete from pesanan where NIK='"+nik.getText()+"'");
            JOptionPane.showMessageDialog(null, "Hapus Pelanggan Sukses");
            tampilkan();
            bersih();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Hapus Pelanggan Gagal");
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void KembaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliaActionPerformed
        new menuawal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KembaliaActionPerformed

    private void tpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpelangganMouseClicked
int i = tpelanggan.getSelectedRow();
if (i>-1){
        nik.setText(model.getValueAt(i, 0).toString());
        np.setText(model.getValueAt(i, 1).toString());
        ap.setText(model.getValueAt(i, 2).toString());
        tp.setText(model.getValueAt(i, 3).toString());
}// TODO add your handling code here:
    }//GEN-LAST:event_tpelangganMouseClicked

    private void npActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        try {
            File reportpelanggan = new File("src/report/reportcustomer.jasper");
            JasperPrint jp = JasperFillManager.fillReport(reportpelanggan.getPath(), null, Koneksi.getKoneksi());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kembalia;
    private javax.swing.JTextField ap;
    private javax.swing.JButton cetak;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField np;
    private javax.swing.JTextField tp;
    private javax.swing.JTable tpelanggan;
    // End of variables declaration//GEN-END:variables
private void tampilkan() {
    int row = tpelanggan.getRowCount();
    for (int a= 0; a<row;a++){
        model.removeRow(0);
    }
    try {
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
         ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM customer");
         while (rs.next()){
             String data []= {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)};
             model.addRow(data);
         }
    } catch (SQLException ex) {
        Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
    }

}
}
