/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import com.mysql.jdbc.PreparedStatement;
import database.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author DIKYPUT PC
 */
public class loginandregister extends javax.swing.JFrame {
 private Connection conn = new Koneksi().getKoneksi();
    public loginandregister() {
        initComponents();
        
    }
    public void bersih() {
emailr.setText("");
passr.setText("");
jk.setText("");
namar.setText("");
alamatr.setText("");
kpr.setText("");
teleponr.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KembaliLR = new javax.swing.JButton();
        KembaliLR1 = new javax.swing.JButton();
        login = new javax.swing.JButton();
        ltxemail = new javax.swing.JTextField();
        ltxpass = new javax.swing.JPasswordField();
        emailr = new javax.swing.JTextField();
        passr = new javax.swing.JTextField();
        namar = new javax.swing.JTextField();
        jk = new javax.swing.JTextField();
        alamatr = new javax.swing.JTextField();
        kpr = new javax.swing.JTextField();
        teleponr = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KembaliLR.setBackground(new java.awt.Color(255, 51, 51));
        KembaliLR.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        KembaliLR.setForeground(new java.awt.Color(255, 255, 255));
        KembaliLR.setText("Kembali");
        KembaliLR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        KembaliLR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliLRActionPerformed(evt);
            }
        });
        getContentPane().add(KembaliLR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        KembaliLR1.setBackground(new java.awt.Color(0, 153, 255));
        KembaliLR1.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        KembaliLR1.setForeground(new java.awt.Color(255, 255, 255));
        KembaliLR1.setText("Admin");
        KembaliLR1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        KembaliLR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliLR1ActionPerformed(evt);
            }
        });
        getContentPane().add(KembaliLR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 80, 30));

        login.setBackground(new java.awt.Color(0, 153, 255));
        login.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 227, 90, -1));
        getContentPane().add(ltxemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 130, 30));

        ltxpass.setText("jPasswordField1");
        ltxpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ltxpassActionPerformed(evt);
            }
        });
        getContentPane().add(ltxpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 130, -1));

        emailr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailrActionPerformed(evt);
            }
        });
        getContentPane().add(emailr, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 130, -1));
        getContentPane().add(passr, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 130, -1));

        namar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namarActionPerformed(evt);
            }
        });
        getContentPane().add(namar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 130, 20));

        jk.setText("pria/wanita");
        jk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkActionPerformed(evt);
            }
        });
        getContentPane().add(jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 130, 20));

        alamatr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatrActionPerformed(evt);
            }
        });
        getContentPane().add(alamatr, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 130, 20));

        kpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kprActionPerformed(evt);
            }
        });
        getContentPane().add(kpr, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 130, 20));

        teleponr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teleponrActionPerformed(evt);
            }
        });
        getContentPane().add(teleponr, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 130, -1));

        register.setBackground(new java.awt.Color(0, 153, 255));
        register.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 323, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
            try{
        Connection c = Koneksi.getKoneksi();
        Statement s = c.createStatement();
        String sql = "SELECT * FROM tlogin where email='" + ltxemail.getText() +"' and password='"+ ltxpass.getText()+ "'";
        ResultSet r = s.executeQuery(sql);
        if(r.next()){
            JOptionPane.showMessageDialog(null, "Login Sukses"); 
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Pasword Salah");
            ltxpass.requestFocus();
    }
        }catch (SQLException e){
                System.out.println("error");
                }

    }//GEN-LAST:event_loginActionPerformed

    private void ltxpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ltxpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ltxpassActionPerformed

    private void KembaliLRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliLRActionPerformed
        new menuawal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KembaliLRActionPerformed

    private void KembaliLR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliLR1ActionPerformed
        new loginadmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KembaliLR1ActionPerformed

    private void emailrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailrActionPerformed

    private void namarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namarActionPerformed

    private void alamatrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatrActionPerformed

    private void kprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kprActionPerformed

    private void teleponrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teleponrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teleponrActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
    String sql ="INSERT into tlogin values (?,?,?,?,?,?,?)";
        try{
        PreparedStatement stat = (PreparedStatement) conn.prepareStatement(sql);
        stat.setString(1, emailr.getText());    
        stat.setString(2, passr.getText());    
        stat.setString(3, namar.getText());    
        stat.setString(4, jk.getText());    
        stat.setString(5, alamatr.getText());    
        stat.setString(6, kpr.getText());    
        stat.setString(7, teleponr.getText());
        
        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Register Sukses");
        bersih();
        this.dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Register Gagal");
        }
    }//GEN-LAST:event_registerActionPerformed

    private void jkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginandregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginandregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginandregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginandregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginandregister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KembaliLR;
    private javax.swing.JButton KembaliLR1;
    private javax.swing.JTextField alamatr;
    private javax.swing.JTextField emailr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jk;
    private javax.swing.JTextField kpr;
    private javax.swing.JButton login;
    private javax.swing.JTextField ltxemail;
    private javax.swing.JPasswordField ltxpass;
    private javax.swing.JTextField namar;
    private javax.swing.JTextField passr;
    private javax.swing.JButton register;
    private javax.swing.JTextField teleponr;
    // End of variables declaration//GEN-END:variables
}
