/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;
import database.Koneksi;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author DIKYPUT PC
 */
public class loginadmin extends javax.swing.JFrame {

    public loginadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emaila = new javax.swing.JTextField();
        passa = new javax.swing.JPasswordField();
        Kembalia = new javax.swing.JButton();
        Logina = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emaila.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        emaila.setForeground(new java.awt.Color(204, 204, 204));
        emaila.setText("E-mail");
        getContentPane().add(emaila, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 210, 40));

        passa.setText("jPasswordField1");
        getContentPane().add(passa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 210, 40));

        Kembalia.setBackground(new java.awt.Color(255, 51, 51));
        Kembalia.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        Kembalia.setForeground(new java.awt.Color(255, 255, 255));
        Kembalia.setText("Kembali");
        Kembalia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Kembalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliaActionPerformed(evt);
            }
        });
        getContentPane().add(Kembalia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        Logina.setBackground(new java.awt.Color(0, 153, 255));
        Logina.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        Logina.setForeground(new java.awt.Color(255, 255, 255));
        Logina.setText("Login");
        Logina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Logina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginaActionPerformed(evt);
            }
        });
        getContentPane().add(Logina, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/loginadmin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliaActionPerformed
    new loginandregister().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_KembaliaActionPerformed

    private void LoginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginaActionPerformed
    try{
        Connection c = Koneksi.getKoneksi();
        Statement s = c.createStatement();
        String sql = "SELECT * FROM ladmin where email='" + emaila.getText() +"' and password='"+ passa.getText()+ "'";
        ResultSet r = s.executeQuery(sql);
        if(r.next()){
            JOptionPane.showMessageDialog(null, "Login Sukses");
            new menuawal().setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Pasword Salah");
            passa.requestFocus();
    }
        }catch (SQLException e){
                System.out.println("error");
                }
    }//GEN-LAST:event_LoginaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kembalia;
    private javax.swing.JButton Logina;
    private javax.swing.JTextField emaila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passa;
    // End of variables declaration//GEN-END:variables
}
