/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

/**
 *
 * @author DIKYPUT PC
 */
public class menuawal extends javax.swing.JFrame {

    public menuawal() {
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        istimewalayanan = new javax.swing.JButton();
        tentanglayanan = new javax.swing.JButton();
        kontaklayanan = new javax.swing.JButton();
        loginregister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        istimewalayanan.setBackground(new java.awt.Color(0, 153, 255));
        istimewalayanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/istimewa.png"))); // NOI18N
        getContentPane().add(istimewalayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 110, 80));

        tentanglayanan.setBackground(new java.awt.Color(0, 153, 255));
        tentanglayanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tentang.png"))); // NOI18N
        getContentPane().add(tentanglayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 110, 80));

        kontaklayanan.setBackground(new java.awt.Color(0, 153, 255));
        kontaklayanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kontaklayanan.png"))); // NOI18N
        getContentPane().add(kontaklayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 110, 80));

        loginregister.setBackground(new java.awt.Color(0, 153, 255));
        loginregister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/loginregister.png"))); // NOI18N
        loginregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginregisterActionPerformed(evt);
            }
        });
        getContentPane().add(loginregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 110, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/menuawal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginregisterActionPerformed
    new loginandregister().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_loginregisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuawal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton istimewalayanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kontaklayanan;
    private javax.swing.JButton loginregister;
    private javax.swing.JButton tentanglayanan;
    // End of variables declaration//GEN-END:variables
}
